"""2

Revision ID: 6c34bfd62ace
Revises: c0b0eb34e48e
Create Date: 2024-02-06 12:03:13.553089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c34bfd62ace"
down_revision: Union[str, None] = "c0b0eb34e48e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reg-users", sa.Column("is_premium", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reg-users", "is_premium")
    # ### end Alembic commands ###
